### ISSUE TITLE
Add more description in README

### ISSUE THREAD

**Issue by amitxdewangan** [Amit-TheOne/DemoRepository#3]
Add more descriptions about the project
Add information about how to learn GitHub
Add more information about how to use this project.

**Comment by ashish11chawda** [comment]
Hey @Amit-TheOne 👋🏻 

I want to work on this issue. Please assign it to me

**Comment by amitxdewangan** [comment]
Hey @pixan198 
Assigning it to you.
What do you think will be the ETA?

**Comment by ashish11chawda** [comment]
Hey @Amit-TheOne 

I can update in few mins
